avg_a = np.average(av)
    print(f"  Average Induction Factor: {avg_a:.4f}")
    Average_axial_velocity = V * (1 + avg_a)
    ax = df.plot(x='J', y='CT', legend=None, style='b-o')
    exp_data.plot(x='J', y='CT', style='r-s', ax=ax, legend=None)
    df.plot(x='J',y='CP',ax=ax,legend=None)
    exp_data.plot(x='J',y='CP',ax=ax)
    plt.ylabel('$C_T$ , $C_P$')
    ax2 = ax.twinx()
    df.plot(x='J', y='Efficiency', style='g-o', ax=ax, legend=None)
    exp_data.plot(x='J', y='eta', style='m-s', ax=ax2, legend=None)
    plt.xlabel('J')
    plt.ylabel('$eta$')
    plt.title('thrust coeff vs Advance Ratio')
    plt.show()
    
    df['Thrust_per_unit_Area'] = df['Thrust (N)'] / A
    df.plot(x='Velocity (m/s)', y='Thrust_per_unit_Area', legend=None, style='b-o')
    plt.title('Thrust vs Velocity')
    plt.show()
    df.to_csv('bemt_output.csv', index=False, columns=['Velocity (m/s)', 'Thrust_per_unit_Area'])
